// Plain-English glossary covering every term in the book’s Appendix A.
// `lesson` links to where the term is explained.
export type Entry = { term: string; def: string; lesson?: string };

export const glossary: Entry[] = [
  { term: "Activation function", def: "A small non-linear ‘squish’ between layers (like ReLU: negatives become 0) so that stacking layers actually adds power instead of collapsing into one big matmul.", lesson: "neural-networks" },
  { term: "Active–active", def: "A reliability setup where several regions or clusters all serve live traffic at the same time. If one fails, the others just keep going.", lesson: "multi-cloud" },
  { term: "Active–passive", def: "A reliability setup with a ‘hot standby’: a backup cluster sits ready but idle, and traffic switches to it only if the main one fails.", lesson: "multi-cloud" },
  { term: "Ada Lovelace (architecture)", def: "NVIDIA’s graphics-focused GPU generation from 2022 (e.g. L4, L40). Good for small models and tight budgets, not for big LLMs.", lesson: "gpu-generations" },
  { term: "Agent", def: "An AI app that takes actions, not just answers questions. Agents usually make many inference calls, often across several models, and use tools.", lesson: "know-your-app" },
  { term: "AI-native application", def: "A product whose core experience depends on generative models. Its needs (modality, speed, cost, usage pattern) should drive every inference decision.", lesson: "know-your-app" },
  { term: "Ampere (architecture)", def: "An older NVIDIA GPU generation (e.g. A100). Still around in legacy setups, but Hopper and Blackwell beat it on speed and cost.", lesson: "gpu-generations" },
  { term: "API", def: "Application Programming Interface: a structured way to send requests and get responses. Inference engines expose an API you call to query a model.", lesson: "inference-engines" },
  { term: "Arithmetic intensity", def: "How much math a piece of work does per byte of data it moves. Low = memory-bound, high = compute-bound (compare with the GPU’s ops:byte ratio).", lesson: "bottlenecks" },
  { term: "Attention", def: "The mechanism that lets each token figure out which earlier tokens matter to it, using queries, keys, and values. A top optimization target.", lesson: "attention-and-kv-cache" },
  { term: "Automatic Speech Recognition (ASR)", def: "Models that turn speech into text, like Whisper. Most of the time goes into the decoder, so LLM-style tricks help a lot.", lesson: "speech" },
  { term: "Autoregressive", def: "Generating output one piece at a time, where each new piece depends on everything before it. How LLMs write: prefill, then decode.", lesson: "how-llms-write" },
  { term: "Autoscaling", def: "Automatically adding or removing copies (replicas) of a model based on traffic, so you meet your speed targets without paying for idle GPUs.", lesson: "autoscaling" },
  { term: "Autoscaling window", def: "How far back the autoscaler looks when deciding to scale. Long windows keep things steady; short windows react faster to spikes.", lesson: "autoscaling" },
  { term: "B200", def: "NVIDIA Blackwell datacenter GPU: 192 GB of memory, 8 TB/s bandwidth, about 5 petaFLOPS of FP8 compute.", lesson: "gpu-generations" },
  { term: "B300", def: "NVIDIA Blackwell datacenter GPU: 288 GB of memory, 8 TB/s bandwidth, about 5 petaFLOPS of FP8 compute.", lesson: "gpu-generations" },
  { term: "Bandwidth", def: "How much data per second can flow through memory (like VRAM) or a connection between chips (like NVLink).", lesson: "bottlenecks" },
  { term: "Baselines", def: "Careful measurements of speed and quality taken before you optimize anything, so you can tell what actually helped or hurt.", lesson: "benchmarking" },
  { term: "Batching", def: "Serving many requests at the same time on one GPU. The weights are read once and shared, so total throughput goes way up.", lesson: "bottlenecks" },
  { term: "Batch sizing", def: "Choosing how many requests to process together. Bigger batches mean more total throughput but slower responses for each user.", lesson: "autoscaling" },
  { term: "Benchmark (intelligence)", def: "A test of how smart a model is, e.g. how many questions it answers correctly (like MMLU).", lesson: "choosing-a-model" },
  { term: "Benchmark (performance)", def: "A measurement of how fast a model deployment is (latency and throughput) under a defined workload.", lesson: "benchmarking" },
  { term: "BF16", def: "A 16-bit number format with a bigger exponent than FP16. It can represent a wider range of values, which helps preserve unusually large numbers.", lesson: "quantization" },
  { term: "Bin packing (multi-cloud)", def: "Treating GPUs scattered across clouds, regions, and clusters as one big pool and fitting workloads into it efficiently.", lesson: "multi-cloud" },
  { term: "Blackwell (architecture)", def: "NVIDIA’s late-2024 GPU generation (B200, B300). Adds FP4 support, microscaling number formats, and very high memory bandwidth.", lesson: "gpu-generations" },
  { term: "BLAS", def: "Basic Linear Algebra Subprograms: a standard set of core math operations (like matrix multiplication) that libraries implement.", lesson: "cuda-and-kernels" },
  { term: "Blue-green deployment", def: "Running two production environments side by side and switching traffic between them, so you can deploy with no downtime and roll back instantly.", lesson: "shipping" },
  { term: "Bottleneck", def: "Whichever resource (compute or memory bandwidth) is maxed out and holding everything else back.", lesson: "bottlenecks" },
  { term: "Cache-aware routing", def: "Sending a request to the replica that already has its prefix (or needed LoRA) cached, so it can skip work and respond faster.", lesson: "caching" },
  { term: "Canary deployment", def: "Rolling out a new version to a small slice of real traffic first, checking it’s healthy, then gradually moving everything over.", lesson: "shipping" },
  { term: "Causal language model", def: "A model that predicts the next token using only the tokens before it. Every modern chatbot LLM is one.", lesson: "how-llms-write" },
  { term: "Chat template", def: "The model-specific format that flattens a conversation (roles, separators, start/end tokens) into a single token sequence.", lesson: "how-llms-write" },
  { term: "Chunked prefill", def: "Splitting a long prompt into chunks so its prefill can be mixed with other work, instead of one long request hogging the GPU.", lesson: "caching" },
  { term: "Classifier-free guidance", def: "In image generation, blending a pass with the prompt and a pass without it on each step. Higher guidance sticks closer to the prompt.", lesson: "image-and-video-models" },
  { term: "CLIP (text encoder)", def: "A text/image encoder used in older image pipelines like SDXL. Newer pipelines often use full LLMs instead for better prompt understanding.", lesson: "image-and-video-models" },
  { term: "Closed model", def: "A model whose weights are private, only usable through the owner’s API (e.g. GPT-5, Claude, Gemini).", lesson: "big-picture" },
  { term: "Cold start", def: "The delay from starting a new replica to its first answer: getting a GPU, starting the container, loading the model, compiling the engine.", lesson: "autoscaling" },
  { term: "ComfyUI", def: "A visual tool for building image-generation pipelines out of swappable parts (base model, refiner, LoRAs, ControlNets).", lesson: "image-and-video-models" },
  { term: "Compute-bound", def: "Limited by how fast the GPU can do math. LLM prefill and image/video generation usually are.", lesson: "bottlenecks" },
  { term: "Context Parallelism (CP)", def: "Copying the model onto several GPUs and splitting the attention context between them. Essential for video models with huge latents.", lesson: "serving-images-video" },
  { term: "Context window", def: "The maximum total number of tokens (input + reasoning + output) a model can handle in one request.", lesson: "how-llms-write" },
  { term: "Continuous batching", def: "Mixing requests together token by token, so a finished request’s slot is filled immediately. Keeps the GPU busy without making users wait. Also called in-flight batching.", lesson: "inference-engines" },
  { term: "Control plane (multi-cloud)", def: "The global ‘brain’ that decides where models get deployed and which resources they get.", lesson: "multi-cloud" },
  { term: "CUDA", def: "NVIDIA’s platform for writing and running programs (kernels) on GPUs, plus the tools to manage GPU memory and execution.", lesson: "cuda-and-kernels" },
  { term: "CUDA Core", def: "A general-purpose math unit on the GPU that handles a wide range of simple operations.", lesson: "gpu-anatomy" },
  { term: "CUDA driver", def: "The low-level layer between your software and the GPU hardware that manages memory and execution.", lesson: "cuda-and-kernels" },
  { term: "CUDA graph", def: "A recorded sequence of GPU operations that can be replayed quickly, cutting overhead for workflows that repeat.", lesson: "cuda-and-kernels" },
  { term: "CUDA kernel", def: "A function that runs in parallel across many GPU threads. The basic unit of GPU work.", lesson: "cuda-and-kernels" },
  { term: "CUDA runtime", def: "The developer-facing CUDA API for launching kernels and managing memory.", lesson: "cuda-and-kernels" },
  { term: "cuBLAS", def: "NVIDIA’s high-quality implementation of BLAS, including fast matrix multiplication (GEMM).", lesson: "cuda-and-kernels" },
  { term: "cuDNN", def: "NVIDIA’s library of building blocks for neural networks on GPUs.", lesson: "cuda-and-kernels" },
  { term: "CuTe", def: "A C++ template library that makes it easier to write tiled, hardware-tuned matrix and fused kernels.", lesson: "cuda-and-kernels" },
  { term: "CUTLASS", def: "An NVIDIA C++ template library of building blocks for writing very fast, GPU-specific matrix multiplication kernels.", lesson: "cuda-and-kernels" },
  { term: "Cross-attention", def: "Attention where one sequence looks at a different one, e.g. an image being generated looking at the text prompt.", lesson: "attention-and-kv-cache" },
  { term: "Data sovereignty", def: "Legal rules about which countries or regions a model’s inputs and outputs are allowed to be processed and stored in.", lesson: "multi-cloud" },
  { term: "Decode", def: "The phase where an LLM writes its answer one token per forward pass. Memory-bound. Sets tokens per second.", lesson: "how-llms-write" },
  { term: "Decoder", def: "A network that uses an internal representation to generate an output. Modern LLMs are decoder-only.", lesson: "neural-networks" },
  { term: "DeepGEMM", def: "A library of clean, fast matrix-multiplication kernels from DeepSeek, especially strong in FP8.", lesson: "cuda-and-kernels" },
  { term: "Denoising model", def: "The heart of an image or video pipeline: it repeatedly refines random noise into a picture, guided by the prompt.", lesson: "image-and-video-models" },
  { term: "Diarization", def: "Figuring out ‘who spoke when’ in an audio recording. Often paired with voice activity detection in speech pipelines.", lesson: "speech" },
  { term: "Diffusers (library)", def: "Hugging Face’s library of reference implementations for image and video generation pipelines.", lesson: "frameworks" },
  { term: "Disaggregation", def: "Running prefill and decode on separate machines that can each scale independently.", lesson: "disaggregation" },
  { term: "Distillation", def: "Training a smaller ‘student’ model to imitate a bigger ‘teacher’, learning from its full probability outputs so it keeps more of its behavior.", lesson: "choosing-a-model" },
  { term: "Docker", def: "A tool for packaging a service and everything it depends on into a standard container that runs the same way anywhere.", lesson: "containers" },
  { term: "Dockerfile", def: "A plain-text recipe of instructions for building a Docker image.", lesson: "containers" },
  { term: "Dynamic batching", def: "Starting a batch when it’s full or a short timer runs out, whichever comes first. Largely replaced by continuous batching for LLMs.", lesson: "autoscaling" },
  { term: "Dynamic range (quantization)", def: "How wide a range of values a number format can represent. Floating-point formats have more range than integers of the same size.", lesson: "quantization" },
  { term: "EAGLE (speculation)", def: "A small, purpose-built draft model that reads the big model’s hidden states to guess several tokens ahead with high accuracy.", lesson: "speculative-decoding" },
  { term: "Elo (quality meta-metric)", def: "A head-to-head scoring system (like in chess) for comparing models by how often people prefer one over another.", lesson: "choosing-a-model" },
  { term: "Embedding model", def: "A model that turns text or images into a fixed-length list of numbers (a vector) capturing meaning. Used for search, RAG, and agent memory.", lesson: "vision-and-embeddings" },
  { term: "Encoder", def: "A network that reads an input and turns it into a rich internal representation (e.g. the audio side of Whisper).", lesson: "neural-networks" },
  { term: "Evals", def: "Tests you design yourself that mirror your real use case, to check whether a model is smart enough for your product.", lesson: "choosing-a-model" },
  { term: "Expert Parallelism (EP)", def: "Spreading the experts of a Mixture-of-Experts model across GPUs, with each GPU holding whole experts. Great for throughput, little communication.", lesson: "parallelism" },
  { term: "Few-step model", def: "An image model trained to produce images in 8 or fewer denoising steps: 80–90% faster, with some loss in quality.", lesson: "image-and-video-models" },
  { term: "Feynman (architecture)", def: "A future NVIDIA GPU generation after Rubin. Few details yet; expect more focus on low precision and memory bandwidth.", lesson: "gpu-generations" },
  { term: "Fine-tuning", def: "Further training a pre-trained model on your domain’s data, often letting a much smaller model do the job well.", lesson: "choosing-a-model" },
  { term: "FlashAttention", def: "A highly optimized way to compute attention that keeps work in fast on-chip memory. Same result, far fewer slow memory trips. Version 3 targets Hopper, 4 targets Blackwell.", lesson: "faster-attention" },
  { term: "Floating-point formats", def: "Number formats like FP16, FP8, and FP4 that store a sign, exponent, and mantissa, giving a wide range of values.", lesson: "quantization" },
  { term: "FLOPS", def: "Floating-point operations per second: how much math a chip can do each second, usually measured on Tensor Cores.", lesson: "bottlenecks" },
  { term: "Forward pass", def: "One full run of input through every layer of the model. In decode, one forward pass = one new token.", lesson: "how-llms-write" },
  { term: "Foundation model", def: "A model trained on broad data that serves as a base for many tasks (e.g. GPT, Claude, Llama), used directly or fine-tuned.", lesson: "choosing-a-model" },
  { term: "Function calling", def: "Giving a model a list of available tools; it responds with which tool to use and the arguments. Also called tool calling or tool use.", lesson: "how-llms-write" },
  { term: "GB200", def: "An NVIDIA ‘superchip’ pairing a Grace CPU with a B200 GPU over a very fast link. Used in NVL72 racks; handy for offloading KV cache and swapping LoRAs.", lesson: "gpu-generations" },
  { term: "GEMM", def: "General matrix-matrix multiplication: the key math operation of inference.", lesson: "cuda-and-kernels" },
  { term: "Generative AI", def: "Models that create new content (text, images, audio, video, code), as opposed to classic ML that only predicts or classifies.", lesson: "big-picture" },
  { term: "GH200", def: "An NVIDIA ‘superchip’ pairing a Grace CPU with an H200 GPU over a very fast link, useful for KV cache offloading and LoRA swapping.", lesson: "gpu-generations" },
  { term: "Goodhart’s Law", def: "“When a measure becomes a target, it ceases to be a good measure.” Why chasing benchmark scores can mislead you.", lesson: "choosing-a-model" },
  { term: "GPT", def: "Generative Pretrained Transformer: OpenAI’s family of LLMs.", lesson: "big-picture" },
  { term: "GPU", def: "Graphics Processing Unit: a massively parallel chip, originally for graphics, now the workhorse for training and running AI models.", lesson: "gpu-anatomy" },
  { term: "GPU node", def: "A standard box of 8 GPUs connected to each other with NVLink and NVSwitch.", lesson: "instances" },
  { term: "Grace CPU", def: "NVIDIA’s ARM-based CPU with a very fast connection to its paired GPU. Used alongside Hopper and Blackwell.", lesson: "gpu-generations" },
  { term: "gRPC", def: "A structured, schema-first protocol that supports streaming in both directions.", lesson: "shipping" },
  { term: "Guidance scale", def: "In image generation, how strongly the model sticks to your prompt vs. being creative.", lesson: "image-and-video-models" },
  { term: "Head (attention)", def: "One of many parallel attention operations in a layer, each tending to track a different kind of relationship.", lesson: "attention-and-kv-cache" },
  { term: "Hidden state", def: "The in-between output of a hidden layer, a list of numbers representing what the model is ‘thinking’ at that point.", lesson: "neural-networks" },
  { term: "High-Bandwidth Memory (HBM)", def: "The very fast memory stacked next to datacenter GPUs. Generations include HBM3, HBM3e, and HBM4.", lesson: "gpu-anatomy" },
  { term: "Hopper (architecture)", def: "NVIDIA’s 2022 GPU generation (H100, H200). Added FP8 support and new asynchronous programming features.", lesson: "gpu-generations" },
  { term: "Hyperscaler", def: "The big general-purpose cloud providers, like AWS, Google Cloud, and Azure.", lesson: "multi-cloud" },
  { term: "Image generation pipeline", def: "The chain of models behind an image generator: a text encoder, an iterative denoiser, and a VAE.", lesson: "image-and-video-models" },
  { term: "Inference", def: "Serving AI models in production: using a trained model to answer real requests.", lesson: "big-picture" },
  { term: "Inference engine", def: "Specialized software (vLLM, SGLang, TensorRT-LLM) that runs models fast, with batching, caching, quantization, and speculation built in.", lesson: "inference-engines" },
  { term: "InfiniBand", def: "A fast network for connecting separate GPU machines. Much faster than regular Ethernet, but much slower than NVLink inside a machine.", lesson: "parallelism" },
  { term: "Input sequence", def: "The tokens you send to the model (prompt, history, tools). Processed during prefill.", lesson: "how-llms-write" },
  { term: "Input Sequence Length (ISL)", def: "How many tokens are in a request’s input.", lesson: "measuring-speed" },
  { term: "Instance (cloud)", def: "A rented virtual machine: GPUs plus CPU, RAM, storage, networking, and interconnect.", lesson: "instances" },
  { term: "Integer formats", def: "Number formats like INT8 and INT4. Simple and compact, but with a limited range of values.", lesson: "quantization" },
  { term: "Inter-token latency (ITL)", def: "The time between tokens as they stream out. 2 ms per token means 500 tokens per second.", lesson: "measuring-speed" },
  { term: "In-flight batching", def: "Another name for continuous batching: mixing requests token by token for high GPU use with steady latency.", lesson: "inference-engines" },
  { term: "Jitter traffic", def: "Adding randomness to request timing and sizes during benchmarks so the test looks more like real traffic.", lesson: "benchmarking" },
  { term: "Kernel fusion", def: "Combining two or more GPU kernels into one, so intermediate results don’t make a round trip through slow memory.", lesson: "cuda-and-kernels" },
  { term: "KV cache", def: "Saved keys and values for all previous tokens, so decode never recomputes them. Saves compute, costs GPU memory.", lesson: "attention-and-kv-cache" },
  { term: "L0/L1/L2 caches (GPU)", def: "Layers of small, fast on-chip memory on a GPU, from tiny and fastest (L0) to larger and shared (L2).", lesson: "gpu-anatomy" },
  { term: "Large Language Model (LLM)", def: "A generative model that takes text in and writes new text out, like GPT, Claude, Llama, or DeepSeek.", lesson: "how-llms-write" },
  { term: "Latency percentiles", def: "Measuring latency as P50/P90/P95/P99 so you see both the typical and the worst-case experience, not just an average.", lesson: "measuring-speed" },
  { term: "Latent consistency", def: "A few-step image technique that predicts the finished latent directly (maybe refining a few times). Very fast, somewhat lower quality.", lesson: "image-and-video-models" },
  { term: "Latent space", def: "A compressed internal version of an image or video (~1% of the pixels) that the denoiser works in.", lesson: "image-and-video-models" },
  { term: "Load testing", def: "Sending sustained heavy traffic to find throughput limits and see how queues and autoscaling behave.", lesson: "benchmarking" },
  { term: "Local (edge) inference", def: "Running models directly on people’s own devices, like laptops and phones.", lesson: "beyond-nvidia" },
  { term: "Logit biasing", def: "Nudging or restricting token scores after each step to force valid structured output like JSON or tool calls.", lesson: "how-llms-write" },
  { term: "Logits", def: "The raw scores a model gives every possible next token, before they’re turned into probabilities.", lesson: "how-llms-write" },
  { term: "Lookahead decoding", def: "A speculation trick that builds n-grams during generation to guess upcoming tokens without a separate draft model.", lesson: "speculative-decoding" },
  { term: "LoRA", def: "Low-rank adaptation: a small, lightweight fine-tune. A single service may need to swap between thousands of LoRAs on one base model.", lesson: "choosing-a-model" },
  { term: "Machine learning (ML)", def: "Classic predictive modeling (classification, forecasting), as opposed to generative AI that creates new content.", lesson: "big-picture" },
  { term: "Matmul", def: "Matrix multiplication: multiplying a list of numbers by a grid of weights. The core operation of every neural network.", lesson: "neural-networks" },
  { term: "Matryoshka representations", def: "Embeddings built like nesting dolls: the first part of the vector holds the most meaning, so you can shorten vectors to save space.", lesson: "vision-and-embeddings" },
  { term: "Medusa (speculation)", def: "A speculation method that adds extra prediction heads to the model (via fine-tuning) so it drafts several tokens per pass.", lesson: "speculative-decoding" },
  { term: "Memory bandwidth", def: "How many bytes per second a GPU can move from its memory to its math units.", lesson: "bottlenecks" },
  { term: "Memory-bound", def: "Limited by how fast data can be moved, not by math. LLM decode usually is.", lesson: "bottlenecks" },
  { term: "Microscaling formats", def: "Number formats like MXFP8, MXFP4, and NVFP4 that give each small block of values (e.g. every 32) its own scale factor for better accuracy.", lesson: "quantization" },
  { term: "Mixture of Experts (MoE)", def: "A model with many small ‘expert’ sub-networks where a router activates only a few per token.", lesson: "attention-and-kv-cache" },
  { term: "Model parallelism", def: "Splitting a model’s work across several GPUs, using tensor, expert, or pipeline parallelism depending on size and goals.", lesson: "parallelism" },
  { term: "Multi-cloud capacity management", def: "A global scheduler that places workloads across many cloud providers and regions.", lesson: "multi-cloud" },
  { term: "Multi-Instance GPU (MIG)", def: "Splitting one big GPU into up to 7 smaller, isolated GPUs (up to 8 memory slices, 7 compute slices).", lesson: "instances" },
  { term: "Multi-node inference", def: "Running one model across two or more 8-GPU machines connected by InfiniBand, when one machine doesn’t have enough memory.", lesson: "parallelism" },
  { term: "Neocloud", def: "Newer cloud providers that specialize in GPUs, like CoreWeave and Nebius.", lesson: "multi-cloud" },
  { term: "Neural audio codec", def: "A learned encoder that compresses audio into tokens, plus a decoder that turns tokens back into sound.", lesson: "speech" },
  { term: "NIM", def: "NVIDIA’s pre-packaged, containerized service for running a specific model.", lesson: "containers" },
  { term: "Node", def: "The physical base unit of 8 GPUs linked with NVLink/NVSwitch. Multi-node setups connect nodes with InfiniBand.", lesson: "instances" },
  { term: "NVFP4", def: "NVIDIA’s 4-bit floating-point format with blocks of 16 values and two levels of scale factors.", lesson: "quantization" },
  { term: "NVIDIA Dynamo", def: "An open-source system for large-scale serving: KV cache reuse, disaggregation, and multi-GPU / multi-node orchestration.", lesson: "inference-engines" },
  { term: "NVL72", def: "A rack-scale Blackwell system linking 72 GPUs and 36 CPUs, built for serving giant models at huge throughput.", lesson: "instances" },
  { term: "NVLink", def: "NVIDIA’s very fast direct link between GPUs: up to 900 GB/s on Hopper and 1,800 GB/s on Blackwell.", lesson: "instances" },
  { term: "NVSwitch", def: "A switch on top of NVLink that lets every GPU in a node talk to every other GPU at full speed.", lesson: "instances" },
  { term: "N-gram speculation", def: "Guessing upcoming tokens by reusing sequences that already appeared in the prompt. Extremely effective for code editing.", lesson: "speculative-decoding" },
  { term: "Offline inference", def: "Big batch jobs processed in the background, optimized for cost and throughput rather than speed per request.", lesson: "know-your-app" },
  { term: "Omni-modal", def: "Models that take several kinds of input (text, images, video, audio) and can produce several kinds of output.", lesson: "vision-and-embeddings" },
  { term: "Online inference", def: "Real-time serving where someone is waiting, optimized for tight latency.", lesson: "know-your-app" },
  { term: "ONNX", def: "A standard, portable format and runtime for machine learning models.", lesson: "frameworks" },
  { term: "Open model", def: "A model whose weights anyone can download and run (e.g. Llama, DeepSeek, Whisper). Always check the license.", lesson: "big-picture" },
  { term: "Ops:byte ratio", def: "A GPU’s compute divided by its memory bandwidth (~295 for an H100 in FP16). The balance point between memory- and compute-bound.", lesson: "bottlenecks" },
  { term: "Output sequence", def: "The tokens the model generates during decode.", lesson: "how-llms-write" },
  { term: "Output Sequence Length (OSL)", def: "How many tokens the model generated for a request.", lesson: "measuring-speed" },
  { term: "Out-of-memory error (OOM)", def: "A crash when the GPU runs out of memory for weights, KV cache, or working data.", lesson: "gpu-anatomy" },
  { term: "PagedAttention", def: "Storing the KV cache in small fixed-size pages that can live anywhere in memory, so far less space is wasted.", lesson: "faster-attention" },
  { term: "PCIe (GPU form factor)", def: "GPUs that plug into standard PCIe slots. Usually lower specs and fewer fast-link options than SXM versions.", lesson: "instances" },
  { term: "Perceived TPS", def: "Tokens per second as seen by one user while text streams in. What people usually mean by ‘TPS’.", lesson: "measuring-speed" },
  { term: "Pipeline Parallelism (PP)", def: "Splitting a model’s layers into stages on different GPUs. Works across machines, but some GPUs sit idle waiting (‘bubbles’).", lesson: "parallelism" },
  { term: "Prefill", def: "The phase where an LLM processes the entire prompt at once and builds the KV cache. Compute-bound. Sets time to first token.", lesson: "how-llms-write" },
  { term: "Prefix caching", def: "Reusing the KV cache for a shared beginning of a prompt across requests, skipping repeated prefill. Big TTFT win for chat, code, and agents.", lesson: "caching" },
  { term: "Pretraining", def: "The huge initial training run on broad data that creates a base model.", lesson: "choosing-a-model" },
  { term: "Prompt", def: "The instruction you give a model. For image models it also includes the negative prompt, steps, and guidance.", lesson: "how-llms-write" },
  { term: "PyTorch Profiler", def: "A tool that shows how much CPU time, GPU time, and memory each operation uses.", lesson: "benchmarking" },
  { term: "Quantization", def: "Storing weights (and possibly activations and KV cache) with fewer bits, cutting memory and compute needs.", lesson: "quantization" },
  { term: "Quantization-aware training", def: "Training a model with quantization in mind so it’s already calibrated to run well at low precision.", lesson: "quantization" },
  { term: "Queue (request)", def: "A holding area for extra requests while the autoscaler brings more replicas online.", lesson: "autoscaling" },
  { term: "RAG", def: "Retrieval-augmented generation: fetching relevant documents and adding them to the prompt so the model has more context.", lesson: "vision-and-embeddings" },
  { term: "Real-time factor (RTF)", def: "How much faster than real time a speech model transcribes. An hour of audio in 6 seconds is an RTF of 600.", lesson: "speech" },
  { term: "Ring attention", def: "A context-parallel method where GPUs pass partial attention results around in a ring, easing communication for huge contexts.", lesson: "serving-images-video" },
  { term: "Roofline model", def: "A chart showing whether work is memory-bound (slanted roof) or compute-bound (flat roof) based on arithmetic intensity.", lesson: "bottlenecks" },
  { term: "RoPE", def: "Rotary positional embeddings: a way of telling the model each token’s position using rotations. Helps with long contexts but adds memory cost.", lesson: "caching" },
  { term: "Routing (inference)", def: "Deciding which replica gets each request, based on load, cached prefixes, loaded LoRAs, and request size.", lesson: "autoscaling" },
  { term: "Rubin (architecture)", def: "NVIDIA’s 2026 GPU generation, introducing HBM4 memory and CPX chips for compute-heavy work.", lesson: "gpu-generations" },
  { term: "Sampling", def: "Picking the output token from the logits: greedy (always the top one), or with temperature, top-k, or top-p.", lesson: "how-llms-write" },
  { term: "Scale factor (quantization)", def: "A multiplier stored alongside low-precision values to map them back to their real size.", lesson: "quantization" },
  { term: "Scale to zero", def: "Shutting down all replicas when there’s no traffic and starting them on demand. Needs fast cold starts and good queueing.", lesson: "autoscaling" },
  { term: "SDXL", def: "Stable Diffusion XL: an older but instructive image pipeline (base + refiner + CLIP).", lesson: "image-and-video-models" },
  { term: "Self-attention", def: "Attention where a sequence looks at itself. In LLMs, each token can only look backward (a causal mask).", lesson: "attention-and-kv-cache" },
  { term: "Service Level Agreement (SLA)", def: "A contractual promise about latency, throughput, uptime, or similar.", lesson: "know-your-app" },
  { term: "Service Level Objective (SLO)", def: "An internal target set tighter than the SLA, so you reliably meet the promise.", lesson: "know-your-app" },
  { term: "SGLang", def: "A fast inference engine with a flexible design and particularly strong support for Mixture-of-Experts models.", lesson: "inference-engines" },
  { term: "Shadow traffic", def: "Copying real production requests to a new deployment to test it without affecting users.", lesson: "shipping" },
  { term: "Sliding window attention", def: "Each token only attends to the last w tokens, turning quadratic cost into linear.", lesson: "faster-attention" },
  { term: "SNAC (audio decoder)", def: "A fast audio decoder often used to turn a text-to-speech model’s tokens into sound.", lesson: "speech" },
  { term: "Softmax", def: "A function that turns a list of scores into probabilities that add up to 1. Used in attention and in picking tokens.", lesson: "how-llms-write" },
  { term: "Sparsity (FLOPS)", def: "With 2:4 structured sparsity (half the values are zero), Tensor Cores can skip the zeros. Most inference is dense, so headline ‘sparse’ FLOPS mislead.", lesson: "gpu-anatomy" },
  { term: "Special Function Unit (SFU)", def: "A dedicated GPU unit for special math like sine and cosine, keeping those off the regular cores.", lesson: "gpu-anatomy" },
  { term: "Speculative decoding", def: "Techniques that draft several tokens cheaply and verify them in one pass of the big model, producing more than one token per forward pass.", lesson: "speculative-decoding" },
  { term: "Streaming Multiprocessor (SM)", def: "A GPU’s main building block: a cluster of cores and cache. A GPU has many of them.", lesson: "gpu-anatomy" },
  { term: "Structured output", def: "Model output that must match a schema (like JSON). Enforced by constraining token choices, not just by asking nicely.", lesson: "how-llms-write" },
  { term: "SXM (GPU form factor)", def: "A socketed GPU module with more power and faster connections than PCIe. The standard for serious inference.", lesson: "instances" },
  { term: "Temperature", def: "A setting that makes token picking more predictable (low, e.g. 0.1) or more random and creative (high, e.g. 1.5). 0 = always the top token.", lesson: "how-llms-write" },
  { term: "Tensor Core", def: "A specialized GPU unit for fast mixed-precision matrix multiplication. The most important kind of compute for inference.", lesson: "gpu-anatomy" },
  { term: "Tensor Parallelism (TP)", def: "Splitting each layer’s math across GPUs in the same machine. Best latency per user, but needs constant fast communication.", lesson: "parallelism" },
  { term: "TensorRT", def: "NVIDIA’s optimized inference runtime with fused kernels, quantization, and more.", lesson: "frameworks" },
  { term: "TensorRT-LLM", def: "NVIDIA’s inference engine for LLMs, with a Python API, fused kernels, quantization, and speculative decoding.", lesson: "inference-engines" },
  { term: "Thread", def: "The smallest unit of execution on a GPU. Kernels launch huge numbers of threads at once.", lesson: "cuda-and-kernels" },
  { term: "Throughput", def: "Total work done per unit of time, e.g. total tokens per second across all users.", lesson: "measuring-speed" },
  { term: "Time to first byte (TTFB)", def: "How long until the first byte of the response arrives.", lesson: "measuring-speed" },
  { term: "Time to first token (TTFT)", def: "How long until the first piece of the answer appears. Mostly determined by prefill.", lesson: "measuring-speed" },
  { term: "Token", def: "A chunk of text (a word or part of a word) represented as a number. In English, roughly 4 tokens for every 3 words.", lesson: "how-llms-write" },
  { term: "Tokenizer", def: "The lookup table that converts text to token numbers and back. Not a neural network; more efficient ones make inference faster.", lesson: "how-llms-write" },
  { term: "Tokens per second (TPS)", def: "How fast output streams to a user once it starts. Mostly determined by decode.", lesson: "measuring-speed" },
  { term: "Top-k / Top-p", def: "Settings that restrict next-token choices to the k most likely tokens, or the smallest set adding up to probability p.", lesson: "how-llms-write" },
  { term: "torch.compile", def: "PyTorch’s compiler: captures the model as a graph and picks or fuses kernels for your GPU. Cache the result to cut cold starts.", lesson: "frameworks" },
  { term: "Training", def: "The expensive process of learning a model’s weights from data on big GPU clusters. Happens before inference.", lesson: "big-picture" },
  { term: "Transformer", def: "The neural network design (from 2017) built around attention. The foundation of nearly all generative AI.", lesson: "neural-networks" },
  { term: "Transformers (library)", def: "Hugging Face’s library of reference implementations for LLMs and other transformer models.", lesson: "frameworks" },
  { term: "Triton Inference Server", def: "NVIDIA’s production serving framework that supports many model backends.", lesson: "frameworks" },
  { term: "VAE", def: "Variational autoencoder: converts between an image’s compact latent form and real pixels.", lesson: "image-and-video-models" },
  { term: "Vector database", def: "A database for storing embedding vectors and quickly finding the most similar ones.", lesson: "vision-and-embeddings" },
  { term: "Vector similarity", def: "A measure (like cosine similarity) of how close two embedding vectors are. Close vectors mean similar meaning.", lesson: "vision-and-embeddings" },
  { term: "Vera CPU", def: "NVIDIA’s ARM-based CPU that succeeds Grace, paired with Rubin GPUs.", lesson: "gpu-generations" },
  { term: "Vision-language model (VLM)", def: "A model that takes images or video plus text and writes text back.", lesson: "vision-and-embeddings" },
  { term: "vLLM", def: "A widely used inference engine with broad model and hardware support and good defaults.", lesson: "inference-engines" },
  { term: "Vocabulary", def: "The full list of tokens a model knows, usually over 100,000.", lesson: "how-llms-write" },
  { term: "Voice activity detection (VAD)", def: "A small model that finds the parts of audio that contain speech, so transcription can skip silence and split into chunks.", lesson: "speech" },
  { term: "VRAM", def: "The GPU’s own memory, holding weights, KV cache, and working data. Its size limits model size; its bandwidth limits decode speed.", lesson: "gpu-anatomy" },
  { term: "WebSocket", def: "A lightweight two-way streaming connection, ideal for real-time audio and live UIs.", lesson: "shipping" },
  { term: "Weights", def: "The billions of numbers inside a model, learned during training. A ‘70B’ model has 70 billion of them.", lesson: "big-picture" },
  { term: "Weights-only quantization", def: "Quantizing only the linear-layer weights and keeping everything else at higher precision. Safest for quality, smallest speedup.", lesson: "quantization" },
  { term: "Workload plane (multi-cloud)", def: "An individual cluster with GPUs that actually runs inference and serves requests.", lesson: "multi-cloud" },
  { term: "Shared inference", def: "Paying per token to use a public model API that many customers share.", lesson: "know-your-app" },
  { term: "Dedicated deployment", def: "GPUs rented or owned just for your app and paid by the hour, giving you control over speed, uptime, and cost.", lesson: "know-your-app" },
  { term: "Noisy neighbors", def: "Other customers’ traffic on a shared service slowing your requests down.", lesson: "know-your-app" },
  { term: "End-to-end latency", def: "The total time the user actually waits, including network and queueing, not just the model’s own work.", lesson: "measuring-speed" },
  { term: "Total TPS", def: "Tokens per second across every user of a service combined, a throughput measure (vs. perceived TPS for one user).", lesson: "measuring-speed" },
  { term: "Accelerator", def: "Any chip built to run AI math fast: GPUs, TPUs, and similar.", lesson: "beyond-nvidia" },
  { term: "Air-gapped", def: "Hardware that is fully cut off from outside networks, usually for security or compliance.", lesson: "beyond-nvidia" },
  { term: "MMA (matrix multiply-accumulate)", def: "D = A × B + C: the core instruction a Tensor Core executes.", lesson: "gpu-anatomy" },
  { term: "SRAM vs. DRAM", def: "SRAM is tiny, very fast memory on the chip; DRAM (like HBM) is large, slower memory off the chip.", lesson: "gpu-anatomy" },
  { term: "Unified memory", def: "One memory pool shared by the CPU and GPU, as on Apple M-series chips. Great for running big models locally.", lesson: "beyond-nvidia" },
  { term: "Modality", def: "The kind of data a model takes in or puts out: text, images, audio, video.", lesson: "vision-and-embeddings" },
  { term: "Vision encoder", def: "A small model that turns an image into tokens an LLM can read.", lesson: "vision-and-embeddings" },
  { term: "Downsampling", def: "Lowering an image’s resolution or a video’s frame rate so it costs fewer tokens.", lesson: "vision-and-embeddings" },
  { term: "OCR", def: "Optical character recognition: a specialist model that reads text in images.", lesson: "vision-and-embeddings" },
  { term: "Embedding dimensionality", def: "The length of an embedding vector. Longer vectors hold more information but cost more to store and search.", lesson: "vision-and-embeddings" },
  { term: "Cosine similarity", def: "A measure of how closely two vectors point the same way; 1 means identical direction.", lesson: "vision-and-embeddings" },
  { term: "Speech-to-speech model", def: "One model that takes audio in and gives audio out, replacing the ASR → LLM → TTS chain.", lesson: "speech" },
  { term: "Text-to-speech (TTS)", def: "Models that turn text into spoken audio. Modern ones are often fine-tuned LLMs that emit audio tokens.", lesson: "speech" },
  { term: "SageAttention", def: "An 8-bit attention kernel that speeds up video and image models.", lesson: "serving-images-video" },
  { term: "FlashInfer", def: "A library of fast GPU kernels built for LLM serving, such as attention and sampling.", lesson: "cuda-and-kernels" },
  { term: "Kernel selection", def: "Choosing the best available kernel for each operation on a specific GPU.", lesson: "cuda-and-kernels" },
  { term: "safetensors", def: "The standard file format for model weights: numbers only, no code, and fast to load.", lesson: "frameworks" },
  { term: "Profiler", def: "A tool that shows where every millisecond and byte goes (e.g. PyTorch Profiler, Nsight Systems, Nsight Compute).", lesson: "benchmarking" },
  { term: "KV cache offloading", def: "Moving KV cache out of GPU memory into CPU memory or disk when VRAM fills up.", lesson: "caching" },
  { term: "Cache hit / cache miss", def: "Whether the needed KV cache was already stored (fast and cheap) or had to be recomputed with a full prefill.", lesson: "caching" },
  { term: "Eviction", def: "Deleting stored cache to make room, so later requests that needed it become cache misses.", lesson: "caching" },
  { term: "Global KV cache", def: "A KV cache on shared network storage that every replica can read.", lesson: "caching" },
  { term: "Long context", def: "A sequence long enough that its KV cache causes problems, often beyond 32K–128K tokens.", lesson: "caching" },
  { term: "KVBM (KV Block Manager)", def: "The part of NVIDIA Dynamo that moves KV cache blocks between memory tiers.", lesson: "caching" },
  { term: "Memory tiers (G1–G4)", def: "Places to keep KV cache, from fastest and smallest to slowest and largest: GPU memory, CPU memory, local SSD, networked storage.", lesson: "caching" },
  { term: "Topology-aware parallelism", def: "Splitting a model across GPUs based on how fast each pair of GPUs can talk to each other.", lesson: "parallelism" },
  { term: "All-reduce", def: "A communication step where every GPU combines its partial result with all the others.", lesson: "parallelism" },
  { term: "Conditional disaggregation", def: "Letting the decode engine handle short or cached prompts itself and only sending big prefills to separate prefill engines.", lesson: "disaggregation" },
  { term: "xPyD", def: "Shorthand for the mix of prefill and decode engines, e.g. 5P3D = five prefill and three decode.", lesson: "disaggregation" },
  { term: "NIXL", def: "NVIDIA’s transfer library used by Dynamo to move KV caches between engines.", lesson: "disaggregation" },
  { term: "Post-training quantization", def: "Converting a finished model’s weights to lower precision, often using calibration data to keep accuracy.", lesson: "quantization" },
  { term: "Granularity (quantization)", def: "How many values share one scale factor: a whole tensor, a channel, or a small block.", lesson: "quantization" },
  { term: "Exponent and mantissa", def: "In a floating-point number, the exponent bits set its size and the mantissa bits carry its detail.", lesson: "quantization" },
  { term: "FP8 (E4M3)", def: "An 8-bit float with 4 exponent and 3 mantissa bits. The sweet spot for inference quantization.", lesson: "quantization" },
  { term: "GGUF", def: "A popular file format for sharing heavily quantized models, mostly for local inference.", lesson: "quantization" },
  { term: "Perplexity", def: "How ‘surprised’ a model is by known text. Lower is better; a quick check that quantization didn’t hurt quality.", lesson: "quantization" },
  { term: "Draft token", def: "A cheaply guessed token waiting to be checked by the big model.", lesson: "speculative-decoding" },
  { term: "Target model", def: "In speculative decoding, the big model whose output you’re speeding up.", lesson: "speculative-decoding" },
  { term: "Token acceptance rate", def: "The share of draft tokens the target model accepts. Higher means bigger speedups.", lesson: "speculative-decoding" },
  { term: "Container", def: "A running, isolated environment that holds an app and all its dependencies.", lesson: "containers" },
  { term: "Container image", def: "The packaged blueprint a container starts from.", lesson: "containers" },
  { term: "Registry", def: "A central place to store and share container images, e.g. Docker Hub.", lesson: "containers" },
  { term: "Pinning (dependencies)", def: "Fixing every dependency to an exact version so builds are repeatable.", lesson: "containers" },
  { term: "Kubernetes", def: "An open-source system that runs and manages containers across a cluster of machines.", lesson: "containers" },
  { term: "Replica", def: "One running copy of a model’s service on its own hardware.", lesson: "autoscaling" },
  { term: "Concurrency target", def: "How many requests one replica should handle at once. It should line up with the batch size.", lesson: "autoscaling" },
  { term: "Scale-down delay", def: "How long to wait before removing replicas after traffic drops, in case it spikes again.", lesson: "autoscaling" },
  { term: "Load balancer", def: "Spreads traffic across replicas that could serve it; a router decides where it should go.", lesson: "autoscaling" },
  { term: "Independent component scaling", def: "Scaling each model in a multi-model pipeline on its own, based on its own load.", lesson: "autoscaling" },
  { term: "Reserved / on-demand / spot", def: "Ways to buy GPUs: long commitment and cheap; flexible and pricier; discounted but can be taken back at any time.", lesson: "multi-cloud" },
  { term: "Total cost of ownership (TCO)", def: "The full cost of running inference: GPUs plus the engineering time to build and operate it.", lesson: "shipping" },
  { term: "Asynchronous inference", def: "Fire-and-forget requests whose results are delivered later, often to a webhook URL.", lesson: "shipping" },
  { term: "Webhook", def: "A URL your system provides so another service can send results to it when they’re ready.", lesson: "shipping" },
  { term: "Streaming", def: "Sending output piece by piece as it’s generated, so users see text (or hear audio) right away.", lesson: "shipping" },
];
