// Plain-English glossary. `lesson` links to where the term is explained.
export type Entry = { term: string; def: string; lesson?: string };

export const glossary: Entry[] = [
  { term: "Activation function", def: "A small non-linear ‘squish’ between layers (like ReLU: negatives become 0) so that stacking layers actually adds power.", lesson: "neural-networks" },
  { term: "Arithmetic intensity", def: "How much math a piece of work does per byte of data it moves. Low = memory-bound, high = compute-bound.", lesson: "bottlenecks" },
  { term: "Attention", def: "The mechanism that lets each token figure out which earlier tokens matter to it, using queries, keys, and values.", lesson: "attention-and-kv-cache" },
  { term: "Autoregressive", def: "Generating output one piece at a time, where each new piece depends on everything before it. How LLMs write.", lesson: "neural-networks" },
  { term: "Batching", def: "Serving many requests at the same time on one GPU. The weights are read once and shared, so total throughput goes way up.", lesson: "bottlenecks" },
  { term: "Bottleneck", def: "Whichever resource (compute or memory bandwidth) is maxed out and holding everything else back.", lesson: "bottlenecks" },
  { term: "Causal language model", def: "A model that predicts the next token using only the tokens before it. Every modern chatbot LLM is one.", lesson: "how-llms-write" },
  { term: "Chat template", def: "The model-specific format that flattens a conversation (roles, tools, messages) into a single token sequence.", lesson: "how-llms-write" },
  { term: "Closed model", def: "A model whose weights are private, only usable through the owner’s API (e.g. GPT, Claude).", lesson: "big-picture" },
  { term: "Compute-bound", def: "Limited by how fast the GPU can do math. LLM prefill and image/video generation usually are.", lesson: "bottlenecks" },
  { term: "Context window", def: "The maximum total number of tokens (input + reasoning + output) a model can handle in one request.", lesson: "how-llms-write" },
  { term: "Cross-attention", def: "Attention where one sequence looks at a different one, e.g. an image being generated looking at the text prompt.", lesson: "attention-and-kv-cache" },
  { term: "Decode", def: "The phase where an LLM writes its answer one token per forward pass. Memory-bound. Sets tokens per second.", lesson: "how-llms-write" },
  { term: "Decoder", def: "A network that uses an internal representation to generate an output. Modern LLMs are decoder-only.", lesson: "neural-networks" },
  { term: "Denoising / diffusion", def: "Generating an image or video by starting from random noise and cleaning it up over many steps.", lesson: "image-and-video-models" },
  { term: "Distillation", def: "Training a smaller or faster model to imitate a bigger one.", lesson: "image-and-video-models" },
  { term: "Encoder", def: "A network that reads an input and turns it into a rich internal representation.", lesson: "neural-networks" },
  { term: "Few-step model", def: "An image model trained to produce images in 8 or fewer denoising steps: much faster, somewhat lower quality.", lesson: "image-and-video-models" },
  { term: "FlashAttention", def: "A highly optimized way to compute attention that keeps work in fast on-chip memory. Same result, far fewer slow memory trips.", lesson: "faster-attention" },
  { term: "FLOPS", def: "Floating-point operations per second: how much math a chip can do each second.", lesson: "bottlenecks" },
  { term: "Forward pass", def: "One full run of input through every layer of the model. In decode, one forward pass = one new token.", lesson: "how-llms-write" },
  { term: "Guidance scale", def: "In image generation, how strongly the model sticks to your prompt vs. being creative.", lesson: "image-and-video-models" },
  { term: "Head (attention)", def: "One of many parallel attention operations in a layer, each tending to track a different kind of relationship.", lesson: "attention-and-kv-cache" },
  { term: "Hidden state", def: "The in-between output of a hidden layer, a list of numbers representing what the model is ‘thinking’ at that point.", lesson: "neural-networks" },
  { term: "Inference", def: "Using a trained model to produce outputs for real requests. The second stage of a model’s life, after training.", lesson: "big-picture" },
  { term: "KV cache", def: "Saved keys and values for all previous tokens, so decode never recomputes them. Saves compute, costs GPU memory.", lesson: "attention-and-kv-cache" },
  { term: "Latent space", def: "A compressed internal version of an image (~1% of the pixels) that image models do their work in.", lesson: "image-and-video-models" },
  { term: "Logits", def: "The raw scores a model gives every possible next token, before they’re turned into probabilities.", lesson: "how-llms-write" },
  { term: "LoRA", def: "A small, lightweight fine-tune that changes a model’s behavior or style without changing its architecture.", lesson: "image-and-video-models" },
  { term: "Matmul", def: "Matrix multiplication: multiplying a list of numbers by a grid of weights. The core operation of every neural network.", lesson: "neural-networks" },
  { term: "Memory bandwidth", def: "How many bytes per second a GPU can move from its memory to its math units.", lesson: "bottlenecks" },
  { term: "Memory-bound", def: "Limited by how fast data can be moved, not by math. LLM decode usually is.", lesson: "bottlenecks" },
  { term: "Mixture of Experts (MoE)", def: "A model with many small ‘expert’ sub-networks where a router activates only a few per token.", lesson: "attention-and-kv-cache" },
  { term: "Open model", def: "A model whose weights anyone can download and run (e.g. Llama, DeepSeek, Qwen). Check the license.", lesson: "big-picture" },
  { term: "Ops:byte ratio", def: "A GPU’s compute divided by its memory bandwidth (~295 for an H100). The balance point between memory- and compute-bound.", lesson: "bottlenecks" },
  { term: "PagedAttention", def: "Storing the KV cache in small pages that can live anywhere in memory, so far less space is wasted.", lesson: "faster-attention" },
  { term: "Prefill", def: "The phase where an LLM processes the entire prompt at once and builds the KV cache. Compute-bound. Sets time to first token.", lesson: "how-llms-write" },
  { term: "Roofline model", def: "A chart showing whether work is memory-bound (slanted roof) or compute-bound (flat roof) based on arithmetic intensity.", lesson: "bottlenecks" },
  { term: "Self-attention", def: "Attention where a sequence looks at itself. In LLMs, each token can only look backward (a causal mask).", lesson: "attention-and-kv-cache" },
  { term: "Sliding window attention", def: "Each token only attends to the last w tokens, turning quadratic cost into linear.", lesson: "faster-attention" },
  { term: "Temperature", def: "A setting that makes token picking more predictable (low) or more random and creative (high). 0 = always the top token.", lesson: "how-llms-write" },
  { term: "Time to first token (TTFT)", def: "How long until the first piece of the answer appears. Mostly determined by prefill.", lesson: "how-llms-write" },
  { term: "Token", def: "A chunk of text (a word or part of a word) represented as a number. The unit LLMs read and write.", lesson: "how-llms-write" },
  { term: "Tokenizer", def: "The lookup table that converts text to token numbers and back. Not a neural network.", lesson: "how-llms-write" },
  { term: "Tokens per second (TPS)", def: "How fast output streams once it starts. Mostly determined by decode.", lesson: "how-llms-write" },
  { term: "Top-k / Top-p", def: "Settings that restrict next-token choices to the k most likely tokens, or the smallest set adding up to probability p.", lesson: "how-llms-write" },
  { term: "Training", def: "The expensive process of learning a model’s weights from data. Happens before inference.", lesson: "big-picture" },
  { term: "Transformer", def: "The neural network design (from 2017) built around attention. The foundation of nearly all generative AI.", lesson: "neural-networks" },
  { term: "VAE", def: "Variational autoencoder: converts between an image’s compact latent form and real pixels.", lesson: "image-and-video-models" },
  { term: "Vocabulary", def: "The full list of tokens a model knows, usually over 100,000.", lesson: "how-llms-write" },
  { term: "Weights", def: "The billions of numbers inside a model, learned during training. A ‘70B’ model has 70 billion of them.", lesson: "big-picture" },
];
