// The book’s Appendix B (Recommended Reading), organized as in the book.
export type Item = { title: string; by: string; url: string; start?: boolean };
export type Section = { name: string; why: string; items: Item[] };

export const nextBooks: Item[] = [
  { title: "AI Engineering: Building Applications with Foundation Models", by: "Chip Huyen (O’Reilly, 2025)", url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/" },
  { title: "Build a Large Language Model (From Scratch)", by: "Sebastian Raschka (Manning, 2024)", url: "https://www.manning.com/books/build-a-large-language-model-from-scratch" },
  { title: "AI Systems Performance Engineering", by: "Chris Fregly (O’Reilly, 2025)", url: "https://www.oreilly.com/library/view/ai-systems-performance/9798341627772/" },
];

export const sections: Section[] = [
  {
    name: "Architecture",
    why: "The original papers behind the models: transformers, diffusion, embeddings, MoE, and more. Heavy reading, but this is where the ideas come from.",
    items: [
      { title: "Attention Is All You Need", by: "Vaswani et al., 2017", url: "https://arxiv.org/abs/1706.03762", start: true },
      { title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", by: "Devlin et al., 2019", url: "https://arxiv.org/abs/1810.04805" },
      { title: "BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and LLMs", by: "Li et al., 2023", url: "https://arxiv.org/abs/2301.12597" },
      { title: "Deep Learning (book)", by: "Goodfellow, Bengio & Courville, 2016", url: "https://www.deeplearningbook.org/" },
      { title: "Deep Learning with Python, 2nd Edition (book)", by: "François Chollet, 2021", url: "https://www.manning.com/books/deep-learning-with-python-second-edition", start: true },
      { title: "Denoising Diffusion Probabilistic Models", by: "Ho et al., 2020", url: "https://arxiv.org/abs/2006.11239" },
      { title: "DiT: Scalable Diffusion Models with Transformers", by: "Peebles & Xie, 2022", url: "https://arxiv.org/abs/2212.09748" },
      { title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness", by: "Dao et al., 2022", url: "https://arxiv.org/abs/2205.14135" },
      { title: "FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning", by: "Dao, 2023", url: "https://arxiv.org/abs/2307.08691" },
      { title: "FlashAttention-3: Fast and Accurate Attention with Asynchrony and Low-precision", by: "Shah et al., 2024", url: "https://arxiv.org/abs/2407.08608" },
      { title: "FlashAttention-4", by: "Tri Dao, Dao AI Lab, 2025", url: "https://github.com/Dao-AILab/flash-attention" },
      { title: "Imagen Video: High Definition Video Generation with Diffusion Models", by: "Ho et al., 2022", url: "https://arxiv.org/abs/2210.02303" },
      { title: "Language Models Are Few-Shot Learners", by: "Brown et al., 2020", url: "https://arxiv.org/abs/2005.14165" },
      { title: "Learning Transferable Visual Models from Natural Language Supervision (CLIP)", by: "Radford et al., 2021", url: "https://arxiv.org/abs/2103.00020" },
      { title: "Longformer: The Long-Document Transformer", by: "Beltagy et al., 2020", url: "https://arxiv.org/abs/2004.05150" },
      { title: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces", by: "Gu & Dao, 2023", url: "https://arxiv.org/abs/2312.00752" },
      { title: "Matryoshka Representation Learning", by: "Kusupati et al., 2022", url: "https://arxiv.org/abs/2205.13147" },
      { title: "Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer", by: "Shazeer et al., 2017", url: "https://arxiv.org/abs/1701.06538" },
      { title: "Reformer: The Efficient Transformer", by: "Kitaev et al., 2020", url: "https://arxiv.org/abs/2001.04451" },
      { title: "Robust Speech Recognition via Large-Scale Weak Supervision (Whisper)", by: "Radford et al., 2022", url: "https://arxiv.org/abs/2212.04356" },
      { title: "RoFormer: Enhanced Transformer with Rotary Position Embedding", by: "Su et al., 2021", url: "https://arxiv.org/abs/2104.09864" },
      { title: "SDXL: Improving Latent Diffusion Models for High-Resolution Image Synthesis", by: "Podell et al., 2023", url: "https://arxiv.org/abs/2307.01952" },
      { title: "Segment Anything", by: "Kirillov et al., 2023", url: "https://arxiv.org/abs/2304.02643" },
      { title: "Sentence-BERT: Sentence Embeddings Using Siamese BERT-Networks", by: "Reimers & Gurevych, 2019", url: "https://arxiv.org/abs/1908.10084" },
      { title: "The Llama 3 Herd of Models", by: "Grattafiori et al., 2024", url: "https://arxiv.org/abs/2407.21783" },
      { title: "Video Diffusion Models", by: "Ho et al., 2022", url: "https://arxiv.org/abs/2204.03458" },
      { title: "Visual Instruction Tuning (LLaVA)", by: "Liu et al., 2023", url: "https://arxiv.org/abs/2304.08485" },
    ],
  },
  {
    name: "Developer tools",
    why: "Docs and repos for the software stack from Chapter 4. Best read with the tool open in front of you.",
    items: [
      { title: "BitsAndBytes", by: "bitsandbytes-foundation", url: "https://github.com/TimDettmers/bitsandbytes" },
      { title: "ComfyUI", by: "comfyanonymous", url: "https://github.com/comfyanonymous/ComfyUI" },
      { title: "CUDA by Example: An Introduction to General-Purpose GPU Programming", by: "Sanders & Kandrot, NVIDIA", url: "https://developer.nvidia.com/cuda-example", start: true },
      { title: "CUDA C++ Programming Guide", by: "NVIDIA", url: "https://docs.nvidia.com/cuda/cuda-c-programming-guide/" },
      { title: "cuBLAS documentation", by: "NVIDIA", url: "https://docs.nvidia.com/cuda/cublas/" },
      { title: "CUTLASS", by: "NVIDIA", url: "https://github.com/NVIDIA/cutlass" },
      { title: "DeepGEMM", by: "DeepSeek AI", url: "https://github.com/deepseek-ai/DeepGEMM" },
      { title: "Hugging Face Diffusers", by: "Hugging Face", url: "https://huggingface.co/docs/diffusers/index" },
      { title: "LMCache", by: "LMCache Project", url: "https://github.com/LMCache/LMCache" },
      { title: "NVIDIA Dynamo documentation", by: "NVIDIA", url: "https://docs.nvidia.com/dynamo/latest/index.html" },
      { title: "NVIDIA Nsight Systems", by: "NVIDIA", url: "https://developer.nvidia.com/nsight-systems" },
      { title: "NVIDIA Triton Inference Server", by: "NVIDIA", url: "https://github.com/triton-inference-server/server" },
      { title: "ONNX Runtime", by: "Microsoft", url: "https://onnxruntime.ai/" },
      { title: "PyTorch Performance Tuning Guide", by: "Szymon Migacz, PyTorch", url: "https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html" },
      { title: "PyTorch Profiler recipe", by: "Shivam Raikundalia, PyTorch", url: "https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html" },
      { title: "SGLang", by: "LMSYS Org", url: "https://github.com/sgl-project/sglang" },
      { title: "TensorRT documentation", by: "NVIDIA", url: "https://docs.nvidia.com/deeplearning/tensorrt/" },
      { title: "TensorRT-LLM", by: "NVIDIA", url: "https://github.com/NVIDIA/TensorRT-LLM" },
      { title: "Transformers", by: "Hugging Face", url: "https://huggingface.co/docs/transformers/index" },
      { title: "vLLM", by: "The Linux Foundation", url: "https://github.com/vllm-project/vllm", start: true },
    ],
  },
  {
    name: "Frontier open models",
    why: "Where the leading open model families live on Hugging Face. Browse the model cards and config.json files to practice reading architectures.",
    items: [
      { title: "DeepSeek", by: "DeepSeek AI", url: "https://huggingface.co/deepseek-ai" },
      { title: "FLUX", by: "Black Forest Labs", url: "https://huggingface.co/black-forest-labs" },
      { title: "Gemma", by: "Google", url: "https://huggingface.co/google" },
      { title: "GLM", by: "Z.ai", url: "https://huggingface.co/zai-org" },
      { title: "GPT OSS", by: "OpenAI", url: "https://huggingface.co/openai" },
      { title: "Kimi", by: "Moonshot AI", url: "https://huggingface.co/moonshotai" },
      { title: "Llama", by: "Meta", url: "https://huggingface.co/meta-llama" },
      { title: "MiniMax", by: "MiniMax AI", url: "https://huggingface.co/MiniMaxAI" },
      { title: "Mistral", by: "Mistral AI", url: "https://huggingface.co/mistralai" },
      { title: "Nemotron", by: "NVIDIA", url: "https://huggingface.co/nvidia" },
      { title: "Orpheus", by: "Canopy Labs", url: "https://huggingface.co/canopylabs" },
      { title: "Qwen", by: "Alibaba Qwen", url: "https://huggingface.co/Qwen" },
      { title: "Wan", by: "Wan-AI", url: "https://huggingface.co/Wan-AI" },
      { title: "Whisper", by: "OpenAI", url: "https://huggingface.co/openai" },
    ],
  },
  {
    name: "GPU infrastructure",
    why: "Hardware and systems: GPU architecture briefs, interconnects, and the classic books on running reliable systems (Chapters 3 and 7).",
    items: [
      { title: "Designing Data-Intensive Applications (book)", by: "Martin Kleppmann, 2017", url: "https://dataintensive.net/" },
      { title: "Grace Hopper / Grace Blackwell systems", by: "NVIDIA", url: "https://www.nvidia.com/en-us/data-center/grace-cpu/" },
      { title: "GPU Glossary", by: "Frye et al., Modal, 2025", url: "https://modal.com/gpu-glossary", start: true },
      { title: "InfiniBand", by: "NVIDIA", url: "https://www.nvidia.com/en-us/networking/products/infiniband/" },
      { title: "Kubernetes documentation", by: "The Kubernetes Authors", url: "https://kubernetes.io/docs/home/" },
      { title: "NVIDIA Blackwell Architecture Technical Brief", by: "NVIDIA, 2025", url: "https://resources.nvidia.com/en-us-blackwell-architecture" },
      { title: "NVIDIA H100 Tensor Core GPU Architecture", by: "NVIDIA, 2023", url: "https://resources.nvidia.com/en-us-hopper-architecture/nvidia-h100-tensor-c" },
      { title: "NVIDIA Tesla: A Unified Graphics and Computing Architecture", by: "Lindholm et al., IEEE Micro, 2008", url: "https://ieeexplore.ieee.org/document/4523358" },
      { title: "NVLink / NVSwitch", by: "NVIDIA", url: "https://www.nvidia.com/en-us/data-center/nvlink/" },
      { title: "Programming Massively Parallel Processors (book)", by: "Hwu, Kirk & El Hajj, 2022", url: "https://www.goodreads.com/work/editions/10244675-programming-massively-parallel-processors-a-hands-on-approach" },
      { title: "SemiAnalysis", by: "Dylan Patel", url: "https://semianalysis.com/" },
      { title: "Site Reliability Engineering: How Google Runs Production Systems (book)", by: "Beyer et al., 2017", url: "https://sre.google/books/" },
    ],
  },
  {
    name: "Inference optimization research",
    why: "The research papers behind Chapter 5’s techniques: quantization, speculation, caching, parallelism, and disaggregation.",
    items: [
      { title: "Adversarial Diffusion Distillation", by: "Sauer et al., 2023", url: "https://arxiv.org/abs/2311.17042" },
      { title: "Train Short, Test Long: Attention with Linear Biases (ALiBi)", by: "Press, Smith & Lewis, 2021", url: "https://arxiv.org/abs/2108.12409" },
      { title: "AWQ: Activation-aware Weight Quantization", by: "Song Han, MIT", url: "https://github.com/mit-han-lab/llm-awq" },
      { title: "Cache-DiT", by: "Vipshop", url: "https://github.com/vipshop/cache-dit" },
      { title: "CacheBlend: Fast LLM Serving for RAG with Cached Knowledge Fusion", by: "Yao et al., 2024", url: "https://arxiv.org/abs/2405.16444" },
      { title: "Adding Conditional Control to Text-to-Image Diffusion Models (ControlNet)", by: "Zhang et al., 2023", url: "https://arxiv.org/abs/2302.05543" },
      { title: "Beyond the Buzz: A Pragmatic Take on Inference Disaggregation", by: "Mitra et al., 2025", url: "https://arxiv.org/abs/2506.05508" },
      { title: "Break the Sequential Dependency of LLM Inference Using Lookahead Decoding", by: "Fu et al., 2024", url: "https://arxiv.org/abs/2402.02057" },
      { title: "EAGLE: Speculative Sampling Requires Rethinking Feature Uncertainty", by: "Li et al., 2024", url: "https://arxiv.org/abs/2401.15077" },
      { title: "EAGLE-2: Faster Inference of Language Models with Dynamic Draft Trees", by: "Li et al., 2024", url: "https://arxiv.org/abs/2406.16858" },
      { title: "EAGLE-3: Scaling up Inference Acceleration via Training-Time Test", by: "Li et al., 2025", url: "https://arxiv.org/abs/2503.01840" },
      { title: "FlashInfer: Efficient and Customizable Attention Engine for LLM Inference Serving", by: "Ye et al., 2025", url: "https://arxiv.org/abs/2501.01005" },
      { title: "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers", by: "Frantar et al., 2022", url: "https://arxiv.org/abs/2210.17323" },
      { title: "High-Resolution Image Synthesis with Latent Diffusion Models", by: "Rombach et al., 2021", url: "https://arxiv.org/abs/2112.10752" },
      { title: "Latent Consistency Models: Synthesizing High-Resolution Images with Few-Step Inference", by: "Luo et al., 2023", url: "https://arxiv.org/abs/2310.04378" },
      { title: "LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale", by: "Dettmers et al., 2022", url: "https://arxiv.org/abs/2208.07339" },
      { title: "Medusa: Simple LLM Inference Acceleration Framework with Multiple Decoding Heads", by: "Cai et al., 2024", url: "https://arxiv.org/abs/2401.10774" },
      { title: "Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism", by: "Shoeybi et al., 2019", url: "https://arxiv.org/abs/1909.08053" },
      { title: "Efficient Memory Management for LLM Serving with PagedAttention", by: "Kwon et al., 2023", url: "https://arxiv.org/abs/2309.06180", start: true },
      { title: "Fast Inference from Transformers via Speculative Decoding", by: "Leviathan et al., 2022", url: "https://arxiv.org/abs/2211.17192", start: true },
      { title: "Ring Attention with Blockwise Transformers for Near-Infinite Context", by: "Liu et al., 2023", url: "https://arxiv.org/abs/2310.01889" },
      { title: "SageAttention: Accurate 8-Bit Attention for Plug-and-play Inference Acceleration", by: "Zhang et al., 2024", url: "https://arxiv.org/abs/2410.02367" },
      { title: "Sequence / Context Parallelism in Megatron-LM", by: "NVIDIA", url: "https://github.com/NVIDIA/Megatron-LM" },
      { title: "SmoothQuant", by: "Song Han, MIT", url: "https://github.com/mit-han-lab/smoothquant" },
      { title: "SparseGPT: Massive Language Models Can Be Accurately Pruned in One-Shot", by: "Frantar & Alistarh, 2023", url: "https://arxiv.org/abs/2301.00774" },
      { title: "SpecVLM: Fast Speculative Decoding in Vision-Language Models", by: "Huang et al., 2025", url: "https://arxiv.org/abs/2509.11815" },
      { title: "TeaCache", by: "Alibaba TongYi Vision Intelligence Lab", url: "https://github.com/ali-vilab/TeaCache" },
    ],
  },
  {
    name: "Intelligence evaluation",
    why: "Benchmarks and guides for measuring model quality, the other half of the job from Chapter 1 and the quantization lesson.",
    items: [
      { title: "ARC Prize", by: "Greg Kamradt, 2025", url: "https://arcprize.org/" },
      { title: "Evals for AI Engineers (book)", by: "Shreya Shankar & Hamel Husain, O’Reilly, 2026", url: "https://www.oreilly.com/library/view/evals-for-ai/9798341660717/", start: true },
      { title: "Grade School Math (GSM8K)", by: "Cobbe & Kosaraju et al., 2021", url: "https://github.com/openai/grade-school-math" },
      { title: "How to Fine-Tune Qwen3 to GPT-4o Level Performance", by: "Greg Schoeninger, Oxen AI, 2025", url: "https://ghost.oxen.ai/how-to-fine-tune-qwen3-to-gpt-4o-level-performance/" },
      { title: "Humanity’s Last Exam", by: "Phan et al., 2025", url: "https://www.lastexam.ai/" },
      { title: "HumanEval: Evaluating LLMs Trained on Code", by: "OpenAI, 2021", url: "https://github.com/openai/human-eval" },
      { title: "MMLU: Measuring Massive Multitask Language Understanding", by: "Hendrycks et al., 2021", url: "https://github.com/hendrycks/test" },
      { title: "MTEB: Massive Text Embedding Benchmark", by: "Muennighoff et al., 2022", url: "https://arxiv.org/abs/2210.07316" },
      { title: "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?", by: "Jimenez et al., 2024", url: "https://www.swebench.com/" },
    ],
  },
];
